# Frases empalagosas San Valentin

# Imports y downloads

## Imports (modulos usados):

In [3]:
#from tensorflow
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk import wordpunct_tokenize
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense
import re
import numpy as np
from sklearn import svm

## Descargas:

In [4]:
nltk.download("popular")

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\violeta.macias\AppData\Roaming\nltk_data
[nltk_data]    |     ...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\violeta.macias\AppData\Roaming\nltk_data
[nltk_data]    |     ...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\violeta.macias\AppData\Roaming\nltk_data
[nltk_data]    |     ...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\violeta.macias\AppData\Roaming\nltk_data
[nltk_data]    |     ...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\violeta.macias\AppData\Roaming\nltk_dat

True

# Creación, preprocesamiento y análisis de datos:

## Creación de los datos:

Tokenizar: Crear una lista de palablas (Tokens) a partir de un texto.

Español:
- str_e    ->  String español 
- lista_e  ->  Lista tokens español

Ingles:
- str_i    ->  String español 
- lista_e  ->  Lista tokens español

### Texto español

#### Crear texto

In [5]:
texto_e = [["¡Te deseo un día de San Valentín increíble, mi amor! sigamos avanzando y trabajando por hacer de nuestros sueños una realidad"], 
["¡Feliz día de San Valentín, mi vida! quiero que sepas cuanto te valoro y el gran lugar qué ocupas en mi corazón. Te amo con locura"]]

In [6]:
texto_e2 = ["Ten un día de San Valentín estupendo, sigamosconstruyendo nuestro amor"]

In [7]:
respuesta_e = ["Muchas gracias, yo a tí tambien", "¿que has dicho?", "felicidades a tí también"]

In [8]:
t_e = []

for i in range(0, len(texto_e)):
    if(i>0):
        t_e =t_e + [" "]
    t_e = t_e + texto_e[i]

print(t_e)

['¡Te deseo un día de San Valentín increíble, mi amor! sigamos avanzando y trabajando por hacer de nuestros sueños una realidad', ' ', '¡Feliz día de San Valentín, mi vida! quiero que sepas cuanto te valoro y el gran lugar qué ocupas en mi corazón. Te amo con locura']


#### Crear string

In [9]:
str_e = ""

for i in range(0, len(t_e)):
    str_e = str_e + str(t_e[i])
print(str_e)

¡Te deseo un día de San Valentín increíble, mi amor! sigamos avanzando y trabajando por hacer de nuestros sueños una realidad ¡Feliz día de San Valentín, mi vida! quiero que sepas cuanto te valoro y el gran lugar qué ocupas en mi corazón. Te amo con locura


https://micro.recursospython.com/recursos/como-quitar-tildes-de-una-cadena.html

#### Quitar signos de puntuacion y dejar las letras en minúsculas

In [10]:
# También se puede usar esto
import string
string.punctuation
str_aux = ""
 # end used to print the output in one line
for i in str_e:
    if i in (string.punctuation+"¡¿"):
        i = "" 
    str_aux = str_aux + i.lower()           # checking for occurence of any punctuation
str_e = str_aux
print(str_e)
        

te deseo un día de san valentín increíble mi amor sigamos avanzando y trabajando por hacer de nuestros sueños una realidad feliz día de san valentín mi vida quiero que sepas cuanto te valoro y el gran lugar qué ocupas en mi corazón te amo con locura


#### Crear stop words

In [11]:
spanish_stopwords = stopwords.words('spanish')
print(spanish_stopwords)

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'e

#### Eliminar stopwords

In [12]:
str_e = " " + str_e + " "
for i in range(0, len(spanish_stopwords)):
    if " " + spanish_stopwords[i] + " " in str_e:
        str_e = str_e.replace(" "+ spanish_stopwords[i] + " ", " ")
str_e = str_e.strip()
print(str_e)

deseo día san valentín increíble amor sigamos avanzando trabajando hacer sueños realidad feliz día san valentín vida quiero sepas cuanto valoro gran lugar ocupas corazón amo locura


#### Quitar tildes

In [13]:
tildes = (
    ("á", "a"),
    ("é", "e"),
    ("í", "i"),
    ("ó", "o"),
    ("ú", "u"),
)
for letra_tilde, letra in tildes:
    str_e = str_e.replace(letra_tilde, letra).replace(letra.upper(), letra_tilde.upper())

print(str_e)

deseo dia san valentin increible amor sigamos avanzando trabajando hacer sueños realidad feliz dia san valentin vida quiero sepas cuanto valoro gran lugar ocupas corazon amo locura


#### Tokenizar

In [14]:
lista_e = str_e.split()
print(lista_e)

['deseo', 'dia', 'san', 'valentin', 'increible', 'amor', 'sigamos', 'avanzando', 'trabajando', 'hacer', 'sueños', 'realidad', 'feliz', 'dia', 'san', 'valentin', 'vida', 'quiero', 'sepas', 'cuanto', 'valoro', 'gran', 'lugar', 'ocupas', 'corazon', 'amo', 'locura']


#### NO ME SALIÓ : Tokenizar + quitar signos de puntuación (no me lo ví bien deja espacios en blanco porque sí)

In [15]:
"""import re
# cargando el texto
lista_e = re.split(r'\W+', str_e.lower())
print(lista_e)"""

"import re\n# cargando el texto\nlista_e = re.split(r'\\W+', str_e.lower())\nprint(lista_e)"

### Texto ingles

#### Crear texto en ingles

In [16]:
texto_i = [["I love you."], ["A hundred hearts would be too few to carry all my love for you."], ["If you were thinking about someone while reading this, you're definitely in love."]]

In [17]:
t_i = []
for i in range(0, len(texto_i)):
    if(i>0):
        t_i =t_i + [" "]
    t_i = t_i + texto_i[i]

print(t_i)

['I love you.', ' ', 'A hundred hearts would be too few to carry all my love for you.', ' ', "If you were thinking about someone while reading this, you're definitely in love."]


#### Crear stop words

In [18]:
english_stopwords = stopwords.words('english')
print(english_stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

#### Crear string en inglés

In [19]:
str_i = ""
for i in range(0, len(t_i)):
    str_i = str_i + str(t_i[i])
print(str_i)

I love you. A hundred hearts would be too few to carry all my love for you. If you were thinking about someone while reading this, you're definitely in love.


#### Quitar signos de puntuacion y dejar las letras en minúsculas

In [20]:
# También se puede usar esto
import string
string.punctuation
str_aux = ""
 # end used to print the output in one line
for i in str_i:
    if i in (string.punctuation+"¡"):
        i = "" 
    str_aux = str_aux + i.lower()           # checking for occurence of any punctuation
str_i = str_aux
print(str_i)

i love you a hundred hearts would be too few to carry all my love for you if you were thinking about someone while reading this youre definitely in love


#### Tokenizar

In [21]:
lista_i = str_i.split()
print(lista_i)

['i', 'love', 'you', 'a', 'hundred', 'hearts', 'would', 'be', 'too', 'few', 'to', 'carry', 'all', 'my', 'love', 'for', 'you', 'if', 'you', 'were', 'thinking', 'about', 'someone', 'while', 'reading', 'this', 'youre', 'definitely', 'in', 'love']


#### NO ME SALIÓ : Tokenizar + quitar signos de puntuación (no me lo ví bien deja espacios en blanco porque sí)

In [22]:
"""import re
# cargando el texto
lista_i = re.split(r'\W+', str_i.lower())
print(lista_i)"""

"import re\n# cargando el texto\nlista_i = re.split(r'\\W+', str_i.lower())\nprint(lista_i)"

## CountVectorizer 

Tokeniza un texto a través de la creación de un vocabulario con las palabras que éste contiene.
<br><br>
Realiza una transformación cuyo objetivo es obtener un mejor tratamiento de los datos.


texto = [["¡Te deseo un día de San Valentín increíble, mi amor! sigamos avanzando y trabajando por hacer de nuestros sueños una realidad"], [""]]


### Normalización de palabras 

Lista con el texto a normalizar:

In [23]:
print(t_e)

['¡Te deseo un día de San Valentín increíble, mi amor! sigamos avanzando y trabajando por hacer de nuestros sueños una realidad', ' ', '¡Feliz día de San Valentín, mi vida! quiero que sepas cuanto te valoro y el gran lugar qué ocupas en mi corazón. Te amo con locura']


Creamos el count_vectorizer con las stopwords españolas:

In [24]:
count_vectorizer = CountVectorizer(stop_words=spanish_stopwords)

In [25]:
text_spanish = count_vectorizer.fit_transform(t_e)

In [26]:
print(text_spanish.toarray())

[[0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1]]


### Tokenización:

In [27]:
count_vectorizer.get_feature_names_out()

array(['amo', 'amor', 'avanzando', 'corazón', 'cuanto', 'deseo', 'día',
       'feliz', 'gran', 'hacer', 'increíble', 'locura', 'lugar', 'ocupas',
       'quiero', 'realidad', 'san', 'sepas', 'sigamos', 'sueños',
       'trabajando', 'valentín', 'valoro', 'vida'], dtype=object)

In [28]:
tx1 = count_vectorizer.fit(t_e)

https://www.educative.io/answers/countvectorizer-in-python

In [29]:
print(tx1.vocabulary_)

{'deseo': 5, 'día': 6, 'san': 16, 'valentín': 21, 'increíble': 10, 'amor': 1, 'sigamos': 18, 'avanzando': 2, 'trabajando': 20, 'hacer': 9, 'sueños': 19, 'realidad': 15, 'feliz': 7, 'vida': 23, 'quiero': 14, 'sepas': 17, 'cuanto': 4, 'valoro': 22, 'gran': 8, 'lugar': 12, 'ocupas': 13, 'corazón': 3, 'amo': 0, 'locura': 11}


### Transformación

Esto es para saber si una palabra del array mostrado en la anterior está presente en esa frase:
- 0 = no está
- 1 = está

In [30]:
print(text_spanish.toarray())

[[0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1]]


In [31]:
print(text_spanish.shape) # Muestra las dimensiones de la variable vector

(3, 24)


## Tfidf transformer

In [32]:
tfidf_transformer = TfidfTransformer()

In [33]:
# text_spanish no tiene stopwords
x_transformed = tfidf_transformer.fit_transform(text_spanish)
print(x_transformed)
#Abcdario =27 letras

  (0, 21)	0.23211804319157203
  (0, 20)	0.30520733245792603
  (0, 19)	0.30520733245792603
  (0, 18)	0.30520733245792603
  (0, 16)	0.23211804319157203
  (0, 15)	0.30520733245792603
  (0, 10)	0.30520733245792603
  (0, 9)	0.30520733245792603
  (0, 6)	0.23211804319157203
  (0, 5)	0.30520733245792603
  (0, 2)	0.30520733245792603
  (0, 1)	0.30520733245792603
  (2, 23)	0.26982521515445296
  (2, 22)	0.26982521515445296
  (2, 21)	0.2052090309921715
  (2, 17)	0.26982521515445296
  (2, 16)	0.2052090309921715
  (2, 14)	0.26982521515445296
  (2, 13)	0.26982521515445296
  (2, 12)	0.26982521515445296
  (2, 11)	0.26982521515445296
  (2, 8)	0.26982521515445296
  (2, 7)	0.26982521515445296
  (2, 6)	0.2052090309921715
  (2, 4)	0.26982521515445296
  (2, 3)	0.26982521515445296
  (2, 0)	0.26982521515445296


## Eliminar los lexemas

En general siempre se prefiere la lematización, puesto que es un buen compromiso entre reducir la cantidad de tokens y preservar un poco más la composición original de estos. El stemming al ser más agresivo tiende a conllevar una pérdida de información más grande.

### Stemming

http://josearcosaneas.github.io/python/r/procesamiento/lenguaje/2017/01/02/procesamiento-lenguaje-natural-0.html#:~:text=El%20stemming%20consiste%20en%20extreaer,ayuda%20de%20la%20librer%C3%ADa%20NLTK.

https://es.linkedin.com/learning/python-para-data-scientist-avanzado/stemming-procesamiento-textual

Una vez ya sepas cómo eliminar todo el ruido más superficial de un texto como, por ejemplo, las "stop words", aquellas palabras que sencillamente no aportan información porque son conjunciones o preposiciones, y todos los signos de puntuación, el siguiente paso normalmente en un análisis de texto es utilizar un "stemmer". ¿Qué es exactamente un "stemmer"? Aquí te propongo usar este, que forma parte del NLTK. Y lo que estamos haciendo cuando usamos una función de este estilo es reducir las palabras a la raíz. Vamos a ver qué es lo que estamos haciendo. Aquí tenemos las palabras sin procesar, y una de las cosas que podemos hacer es reducir todas las conjugaciones del verbo "llegar" a su raíz. Es decir, llevar todas las palabras que sean "llegaba", "llegaban", etc., a "llegar". Esto es lo que hace una función de este estilo. Tenemos que inicializar 'stemmer' en el idioma que lo queremos. Hay bastantes más. El tema es que muchos de ellos no aceptan el español, así que yo recomiendo este si estás trabajando con texto en castellano, pero sabed que existe, por ejemplo, también el PorterStemmer, que también es muy potente. Aquí creamos el objeto. Y lo que vamos a hacer es, usando este "loop", coger cada una de las palabras que tengamos en la lista y vamos a extraer su raíz. He creado una lista de raíces, de momento vacía. Y vamos a extraer la raíz de cada una de ellas. Como puedes ver, es inmediato. Tenemos exactamente el mismo texto, pero hemos despojado a todas las palabras de sus sufijos, es decir, tenemos la raíz. Antes he hablado de "llegar" y ahora solo tenemos la raíz. Esto lo que permite es que, cuando hagamos un recuento de frecuencias, no nos veamos afectados por qué conjugación o qué variante de la palabra estemos usando. Si lo que queremos es usar la función 'FreqDist', de las raíces, cogemos, por ejemplo, las 20 primeras. Vemos efectivamente que no son las palabras en realidad, aunque hay algunas que sí. Señor, por ejemplo, tiene el mismo formato. Pero si este objeto encuentra "señora", también lo va a reducir a "señor". Este es el punto. Y comparamos esto con... Y podemos ver, por ejemplo, que "caballero" ahora es la palabra que más aparece, o la raíz asociada a "caballero", y aquí no lo era, estaba empatada con "nombre". Este proceso que, como has visto, es increíblemente sencillo, consta de crear un objeto y recorrer mediante un bucle todas las palabras que tenemos en nuestra lista. Recomiendo que primero lo limpies con una instrucción de este tipo. Y creamos una transformación de nuestras palabras que permite realizar un análisis mucho más específico que no dependa tanto de las circunstancias concretas.

In [34]:
ps = PorterStemmer()

Tokenizar:
- otra forma:
tokens = [word for word in wordpunct_tokenize(texto_e)]

In [36]:
print(lista_e)

['deseo', 'dia', 'san', 'valentin', 'increible', 'amor', 'sigamos', 'avanzando', 'trabajando', 'hacer', 'sueños', 'realidad', 'feliz', 'dia', 'san', 'valentin', 'vida', 'quiero', 'sepas', 'cuanto', 'valoro', 'gran', 'lugar', 'ocupas', 'corazon', 'amo', 'locura']


Reducir las palabras a lexema y ver su frecuencia (cuantas veces aparecen):

#### Primera prueba para entenderlo

Reduce palabras a su raíz:

In [58]:
tx_es_new = []
num = 0
tx_es = [p for p in lista_e if not p in set(spanish_stopwords)]
for p in tx_es:
    print(p + ":" + ps.stem(p))
    tx_es_new.append(ps.stem(p))
    num = num + 1

print(tx_es)
print(tx_es_new)

deseo:deseo
dia:dia
san:san
valentin:valentin
increible:increibl
amor:amor
sigamos:sigamo
avanzando:avanzando
trabajando:trabajando
hacer:hacer
sueños:sueño
realidad:realidad
feliz:feliz
dia:dia
san:san
valentin:valentin
vida:vida
quiero:quiero
sepas:sepa
cuanto:cuanto
valoro:valoro
gran:gran
lugar:lugar
ocupas:ocupa
corazon:corazon
amo:amo
locura:locura
['deseo', 'dia', 'san', 'valentin', 'increible', 'amor', 'sigamos', 'avanzando', 'trabajando', 'hacer', 'sueños', 'realidad', 'feliz', 'dia', 'san', 'valentin', 'vida', 'quiero', 'sepas', 'cuanto', 'valoro', 'gran', 'lugar', 'ocupas', 'corazon', 'amo', 'locura']
['deseo', 'dia', 'san', 'valentin', 'increibl', 'amor', 'sigamo', 'avanzando', 'trabajando', 'hacer', 'sueño', 'realidad', 'feliz', 'dia', 'san', 'valentin', 'vida', 'quiero', 'sepa', 'cuanto', 'valoro', 'gran', 'lugar', 'ocupa', 'corazon', 'amo', 'locura']


#### Algoritmo Porter

In [47]:
porter_stemmer = PorterStemmer()
stemmers = [porter_stemmer.stem(word) for word in lista_e]
final = [stem for stem in stemmers if stem.isalpha() and len(stem) > 1]

In [46]:
fdist = nltk.FreqDist(final)
print(fdist.most_common(10))

[('dia', 2), ('san', 2), ('valentin', 2), ('deseo', 1), ('increibl', 1), ('amor', 1), ('sigamo', 1), ('avanzando', 1), ('trabajando', 1), ('hacer', 1)]


#### Algoritmo Porter2

In [44]:
sSnowball_stemmer = SnowballStemmer('spanish')
stemmers2 = [sSnowball_stemmer.stem(word) for word in lista_e]
final2 = [stem for stem in stemmers2 if stem.isalpha() and len(stem) > 1]

In [49]:
fdist2 = nltk.FreqDist(final2)
print(fdist2.most_common(10))

[('dia', 2), ('san', 2), ('valentin', 2), ('dese', 1), ('increibl', 1), ('amor', 1), ('sig', 1), ('avanz', 1), ('trabaj', 1), ('hac', 1)]


### Lematización

https://keepcoding.io/blog/que-es-la-lematizacion-en-python/

La lematización agrega contexto a las palabras, es preferible al stemming.

Es una etapa importante en el PLN, está técnica algorítmica consiste en
encontrar la forma morfológica básica de una palabra (lema), para que
esto suceda se agrupan las palabras flexionadas que vendrían siendo
verbos conjugados como: limpiar – limpiando, palabras en distintas
formas como: gato – gata, entre otros, y se analiza como un solo elemento
para encontrar la palabra base (Dereza, 2018) . 

#### WordNetLemmatizer

In [60]:
wordnet_lemmatizer = WordNetLemmatizer()

In [64]:
print(lista_e)
for p in lista_e:
    print("{0:20}{1:20}".format(p, wordnet_lemmatizer.lemmatize(p)))

['deseo', 'dia', 'san', 'valentin', 'increible', 'amor', 'sigamos', 'avanzando', 'trabajando', 'hacer', 'sueños', 'realidad', 'feliz', 'dia', 'san', 'valentin', 'vida', 'quiero', 'sepas', 'cuanto', 'valoro', 'gran', 'lugar', 'ocupas', 'corazon', 'amo', 'locura']
deseo               deseo               
dia                 dia                 
san                 san                 
valentin            valentin            
increible           increible           
amor                amor                
sigamos             sigamos             
avanzando           avanzando           
trabajando          trabajando          
hacer               hacer               
sueños              sueños              
realidad            realidad            
feliz               feliz               
dia                 dia                 
san                 san                 
valentin            valentin            
vida                vida                
quiero              quiero              

In [65]:
for p in lista_e:
    print("{0:20}{1:20}".format(p, wordnet_lemmatizer.lemmatize(p, pos='v')))

deseo               deseo               
dia                 dia                 
san                 san                 
valentin            valentin            
increible           increible           
amor                amor                
sigamos             sigamos             
avanzando           avanzando           
trabajando          trabajando          
hacer               hacer               
sueños              sueños              
realidad            realidad            
feliz               feliz               
dia                 dia                 
san                 san                 
valentin            valentin            
vida                vida                
quiero              quiero              
sepas               sepas               
cuanto              cuanto              
valoro              valoro              
gran                gran                
lugar               lugar               
ocupas              ocupas              
corazon         

#### s

In [74]:
from spacy.tokens import Token
y = Token()
set((y.lemma_.lower() for token in lista_e))

TypeError: __cinit__() takes exactly 3 positional arguments (0 given)

#### Revisar:

In [ ]:
#import spacy

#nlp = spacy.load("es")

#### ?

In [ ]:
import spacy
from spacy import displacy 
from spacy.lang.en import English
# nlp = spacy.load(es_core_news_sm)
# doc = English(str_i) # Crea un objeto de spacy tipo nlp
# tokens = [t.orth_ for t in doc] # Crea una lista con las palabras del texto

In [ ]:
# tokens = normalize(str_i) # crear una lista de tokens
# stems = [spanishstemmer.stem(token) for token in tokens]

# Modelos:

## SVM

In [83]:
algo_llamado_svm = svm.SVC(probability=True)

In [126]:
algo_llamado_svm.fit(x_transformed, respuesta_e) #x = x_transformer, y = respuesta_e

SVC(probability=True)

In [127]:
prediction = algo_llamado_svm.predict(x_transformed2) #acurracy test

ValueError: X has 7 features, but SVC is expecting 24 features as input.

In [123]:
print (u'Accuracy:  {:.1%}'.format(np.mean(prediction == respuesta_e)))

Accuracy:  100.0%


## Secuential

In [83]:
sequential_model = keras.models.Sequential() # Pag 532 cap 16

# Extra

Mirar keras.backend

# Bibliografía

## Preprocesamiento de texto:

https://medium.com/qu4nt/reducir-el-n%C3%BAmero-de-palabras-de-un-texto-lematizaci%C3%B3n-y-radicalizaci%C3%B3n-stemming-con-python-965bfd0c69fa

http://josearcosaneas.github.io/python/r/procesamiento/lenguaje/2017/01/02/procesamiento-lenguaje-natural-0.html#:~:text=El%20stemming%20consiste%20en%20extreaer,ayuda%20de%20la%20librer%C3%ADa%20NLTK.

## Documentación Python

https://www.tensorflow.org/api_docs/python/tf/keras

https://www.tensorflow.org/text/tutorials/nmt_with_attention?hl=es-419

## Ejemplos de chatbot:

https://planetachatbot.com/tutorial-chatbot-usando-nltk-keras/

## backend

https://keras.io/api/utils/backend_utils/

https://faroit.com/keras-docs/1.2.0/backend/

## Proyectos de otra universidad:


https://dspace.ups.edu.ec/bitstream/123456789/22069/1/UPS-CT009621.pdf

https://digital.csic.es/bitstream/10261/227679/1/TFM_VeronicaPinillaGomez%20%281%29.pdf

https://m.riunet.upv.es/bitstream/handle/10251/128834/Gallardo%20-%20Creaci%C3%B3n%20de%20un%20modelo%20predictivo%20para%20clasificar%20las%20consultas%20ciudadanas%20sobre%20el%20tra....pdf?sequence=1&isAllowed=y